name: Make changelogs

on:
  push:
    branches: [master]

jobs:
  MakeCL:
    runs-on: ubuntu-latest
    if: github.repository == 'nuke-ops/Nostra-13' && !contains(github.event.head_commit.message, '[ci skip]')
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2
        with:
          fetch-depth: 25
      - name: Python setup
        uses: actions/setup-python@v4.6.1
        with:
          python-version: '3.x'
      - name: Install depends
        run: |
          python -m pip install --upgrade pip
          pip install ruamel.yaml PyGithub
      - name: Make CL
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} #Use this instead if you have unprotected branches
          #GITHUB_TOKEN: ${{ secrets.CL_TOKEN }}
          GIT_EMAIL: "60018842+nuke-ops@users.noreply.github.com"
          GIT_NAME: "nuke-ops"
        run: python tools/changelog/generate_cl.py
